### ISSUE TITLE
ght assign not reassigning interviewers

### ISSUE THREAD

**Issue by ijansky** [canonical/ght#173]
Running `ght assign` with the config file below does not assign written interviews to individuals. It runs for about 1-2 seconds and then completes.
```
$ ght assign
✔ Using the saved credentials.
✔ Setup is completed.
```
Config file:
```
"Software Engineer, Commercial Systems":
  "Written Interview":
    - name: Real Name
      active: true
...
```
I tried changing the job name to include the role id, without quotes, etc. without any success.

**Comment by anthonydillon** [comment]
I believe it could be the strings in your config?

```yaml
Web Developer:
  Written Interview:
    - name: First name
      active: true
    - name: Second name
      active: true
    - name: Third name
      active: true
```
